### PR TITLE
Added ENV variable for overwriting config files from default-config

### PR DESCRIPTION
**Pull request by sukujgrg**
## Definition of Done

**General**
 - [ ] Branch is up-to-date with master
 - [ ] Code is reviewed and tested by someone in the Kube team
 - [ ] If there are user facing changes (new env variables for example) update the docs and make sure to notify the docs team to update official documentation 

## Why overwriting files from default-conf to ${APP_HOME}/conf dir is helpful?

We have deployed xl-release as a container and `$APP_HOME/conf/` is mounted to a shared volume. If we want to make any changes to configuration files in `${APP_HOME}/config/` (eg: ldap configurations.), the current way is to update the files in the shared mount path of `${APP_HOME}/conf/` as the files from `default-conf/` in docker image won't get copied over if files already exists in `${APP_HOME}/conf`. If force copying of `default-conf/*` to `${APP_HOME}/conf/` can be done, we just need to put our custom configurations in `default-conf/` path of xl-release docker image and on next deployment we will get the new configs in the shared mounted path.

### CODE REVIEW

**Review by karthiksonti24 — CHANGES_REQUESTED** [review]
@sukujgrg 
1. Can you change **FORCECOPY_DEFAULT_CONFIGS** to **FORCECOPY_DEFAULT_CONFIG** for better naming convention. 
2. Is this variable added only for the 9.7 version or else even for the upcoming versions?
3. Is this config not part of xld images, because I see this variable added only for xlr ?

**Comment by sukujgrg** [comment]
> 
> 
> @sukujgrg
> 
>     1. Can you change **FORCECOPY_DEFAULT_CONFIGS** to **FORCECOPY_DEFAULT_CONFIG** for better naming convention.
> 
>     2. Is this variable added only for the 9.7 version or else even for the upcoming versions?
> 
>     3. Is this config not part of xld images, because I see this variable added only for xlr ?

1. Updated ENV name to `FORCECOPY_DEFAULT_CONFIG`.
2. For future versions as well.
3. Updated for xld images.

**Comment by karthiksonti24** [comment]
> > @sukujgrg
> > ```
> > 1. Can you change **FORCECOPY_DEFAULT_CONFIGS** to **FORCECOPY_DEFAULT_CONFIG** for better naming convention.
> > 
> > 2. Is this variable added only for the 9.7 version or else even for the upcoming versions?
> > 
> > 3. Is this config not part of xld images, because I see this variable added only for xlr ?
> > ```
> 
>     1. Updated ENV name to `FORCECOPY_DEFAULT_CONFIG`.
> 
>     2. For future versions as well.
> 
>     3. Updated for xld images.

@sukujgrg If this has to work for 

> > @sukujgrg
> > ```
> > 1. Can you change **FORCECOPY_DEFAULT_CONFIGS** to **FORCECOPY_DEFAULT_CONFIG** for better naming convention.
> > 
> > 2. Is this variable added only for the 9.7 version or else even for the upcoming versions?
> > 
> > 3. Is this config not part of xld images, because I see this variable added only for xlr ?
> > ```
> 
>     1. Updated ENV name to `FORCECOPY_DEFAULT_CONFIG`.
> 
>     2. For future versions as well.
> 
>     3. Updated for xld images.

@sukujgrg 

For future versions, we need to make more changes in other files. I will add them.
Can you please add story details and your team members for more visibility.

**Comment by sukujgrg** [comment]
#### Why overwriting files from `default-conf` to `${APP_HOME}/conf` dir is helpful?
We have deployed xl-release as a container and `$APP_HOME/conf/` is mounted to a shared volume. If we want to make any changes to configuration files in `${APP_HOME}/config/` (eg: ldap configurations.), the current way is to update the files in the shared mount path of `${APP_HOME}/conf/` as the files from `default-conf/` in docker image won't get copied over if files already exists in `${APP_HOME}/conf`. If force copying of `default-conf/*` to `${APP_HOME}/conf/` can be done, we just need to put our custom configurations in `default-conf/` path of xl-release docker image and on next deployment we will get the new configs in the shared mounted path.

**Pull request closed without merging**
